services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    trilobit_contao_constants.listener.insert_tags:
        class: Trilobit\ConstantsBundle\EventListener\InsertTagsListener
        public: true
